### ISSUE TITLE
Break ground for bootcamp

### ISSUE THREAD

**Issue by vtsatskin** [mozilla/community-ux#11]
I'm thinking we should put start piecing together a skeleton for our bootcamp. This would have sections for content proposed in #4. We shouldn't think of these as set in stone, so let's just get something out there and we can refine later.

**Comment by mhanratty** [comment]
Awesome, love the enthusiasm! Since there aren't many folks on the github yet, maybe email the community-ux@mozilla.org and ux-team@mozilla.com lists about the idea of creating a bootcamp so people are aware and can give feedback. I would include the purpose of the bootcamp, why you are so passionate about it (i.e. as an intern this stuff was scattered everywhere or does not even exist), and a link to the webdev bootcamp for reference. You can link to the different github issues for people to get involved, learn more, and give feedback.

**Comment by vtsatskin** [comment]
I've started the Bootcamp on [our wiki](https://wiki.mozilla.org/UX/Bootcamp).
